version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGODB_USER: dev
      MONGODB_PASSWORD: password
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - "mongodb-data:/data/db"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    links:
      - mongodb:mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes:
  mongodb-data:
    external: true
